class_name SeaLaneData
extends Resource
## Pre-computed sea lanes between every pair of ports.
## Generated by tools/build_map_data.gd.
##
## Lane i runs from the first port in keys[i] ("FROM-TO", ids in alphabetical
## order) to the second, through points[starts[i]] .. points[starts[i + 1] - 1].

@export var keys := PackedStringArray()
## Index of each lane's first point; has one extra entry marking the end.
@export var starts := PackedInt32Array()
## (lon, lat) in degrees. Longitudes run continuously along a lane, so a lane
## crossing the Pacific can go past 180.
@export var points := PackedVector2Array()
## Lane lengths in nautical miles.
@export var distances := PackedFloat32Array()
