class_name WorldMapData
extends Resource
## Pre-built world map art in projected map coordinates (see Geo).
## Generated by tools/build_map_data.gd from Natural Earth data.

## Land fill, as a flat list of triangles (3 points each).
@export var land_triangles := PackedVector2Array()
## Lakes and other holes in the land, drawn in the ocean color over the land.
@export var water_triangles := PackedVector2Array()
## Coastline, as pairs of points (one line segment per pair).
@export var coast_segments := PackedVector2Array()
## Land borders between countries, as pairs of points.
@export var border_segments := PackedVector2Array()

@export var label_names := PackedStringArray()
@export var label_positions := PackedVector2Array()
## Web-map zoom level at which each country's name starts showing.
@export var label_min_zoom := PackedFloat32Array()
